const dummyData = {
    categories: [
      { name: "Fish", description: "Fresh sashimi-grade fish & seafood" },
      { name: "Rice & Grains", description: "Sushi rice, seasonings, and grains" },
      { name: "Nori & Wrappers", description: "Seaweed sheets and wrappers" },
      { name: "Sauces & Seasonings", description: "Soy sauce, miso, and core seasonings" },
      { name: "Vegetables & Garnish", description: "Fresh produce and garnish items" },
      { name: "Beverages", description: "Japanese beers, sake, and soft drinks" },
    ],
  
    customizations: [
      // Add-ons (like “toppings”)
      { name: "Extra Wasabi", price: 5, type: "topping" },
      { name: "Extra Pickled Ginger", price: 4, type: "topping" },
      { name: "Extra Nori Sheets", price: 10, type: "topping" },
      { name: "Sesame Seeds", price: 3, type: "topping" },
      { name: "Scallions", price: 4, type: "topping" },
      { name: "Masago (Smelt Roe)", price: 12, type: "topping" },
      { name: "Tobiko (Flying Fish Roe)", price: 14, type: "topping" },
      { name: "Avocado", price: 8, type: "topping" },
  
      // Sides (like “side”)
      { name: "Miso Soup", price: 12, type: "side" },
      { name: "Edamame", price: 15, type: "side" },
      { name: "Seaweed Salad", price: 18, type: "side" },
      { name: "Gyoza", price: 20, type: "side" },
      { name: "Green Tea", price: 10, type: "side" },
      { name: "Asahi Beer", price: 28, type: "side" },
      { name: "Sapporo Beer", price: 28, type: "side" },
      { name: "Kirin Ichiban", price: 28, type: "side" },
      { name: "Ramune Soda", price: 18, type: "side" },
      { name: "Hot Sake", price: 30, type: "side" },
    ],
  
    menu: [
      {
        name: "Sushi Rice (Koshihikari)",
        description: "Premium short-grain rice for sushi prep",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/012/167/211/large_2x/rice-bowl-isolated-on-transparent-background-free-png.png",
        price: 54.99,
        rating: 4.9,
        calories: 360,
        protein: 7,
        category_name: "Rice & Grains",
        customizations: ["Sesame Seeds", "Scallions", "Extra Nori Sheets", "Green Tea"],
      },
      {
        name: "Rice Vinegar",
        description: "Seasoning vinegar for sushi rice (su)",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/031/061/688/large_2x/vinegar-bottle-isolated-on-transparent-background-free-png.png",
        price: 12.99,
        rating: 4.6,
        calories: 15,
        protein: 1,
        category_name: "Sauces & Seasonings",
        customizations: ["Sesame Seeds", "Extra Pickled Ginger", "Green Tea"],
      },
      {
        name: "Nori Sheets (Yaki Nori)",
        description: "Roasted seaweed sheets for rolls and hand rolls",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/032/343/657/large_2x/seaweed-nori-isolated-on-transparent-background-free-png.png",
        price: 29.99,
        rating: 4.7,
        calories: 35,
        protein: 5,
        category_name: "Nori & Wrappers",
        customizations: ["Extra Nori Sheets", "Sesame Seeds", "Scallions", "Seaweed Salad"],
      },
      {
        name: "Yellowtail (Hamachi)",
        description: "Sashimi-grade yellowtail fillet",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/027/311/304/large_2x/fresh-fish-fillet-isolated-on-transparent-background-free-png.png",
        price: 89.99,
        rating: 4.8,
        calories: 146,
        protein: 23,
        category_name: "Fish",
        customizations: ["Extra Wasabi", "Extra Pickled Ginger", "Scallions", "Tobiko (Flying Fish Roe)"],
      },
      {
        name: "Salmon (Sake)",
        description: "Sashimi-grade salmon loin",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/030/515/402/large_2x/salmon-fillet-isolated-on-transparent-background-free-png.png",
        price: 79.99,
        rating: 4.9,
        calories: 208,
        protein: 20,
        category_name: "Fish",
        customizations: ["Extra Wasabi", "Sesame Seeds", "Avocado", "Masago (Smelt Roe)"],
      },
      {
        name: "Tuna (Maguro)",
        description: "Sashimi-grade tuna block for nigiri/sashimi",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/028/241/438/large_2x/tuna-fish-fillet-isolated-on-transparent-background-free-png.png",
        price: 99.99,
        rating: 4.7,
        calories: 132,
        protein: 29,
        category_name: "Fish",
        customizations: ["Extra Wasabi", "Extra Pickled Ginger", "Scallions", "Tobiko (Flying Fish Roe)"],
      },
      {
        name: "Eel (Unagi)",
        description: "Grilled eel portions (frozen/ready for service)",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/029/874/539/large_2x/grilled-fish-isolated-on-transparent-background-free-png.png",
        price: 64.99,
        rating: 4.5,
        calories: 184,
        protein: 18,
        category_name: "Fish",
        customizations: ["Sesame Seeds", "Scallions", "Extra Nori Sheets", "Miso Soup"],
      },
      {
        name: "Shrimp (Ebi)",
        description: "Cooked shrimp for nigiri and rolls",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/027/922/743/large_2x/shrimp-isolated-on-transparent-background-free-png.png",
        price: 42.5,
        rating: 4.4,
        calories: 99,
        protein: 24,
        category_name: "Fish",
        customizations: ["Extra Wasabi", "Extra Pickled Ginger", "Avocado", "Seaweed Salad"],
      },
      {
        name: "Imitation Crab (Kani)",
        description: "Crab sticks for California rolls and salads",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/028/544/506/large_2x/crab-sticks-surimi-isolated-on-transparent-background-free-png.png",
        price: 24.99,
        rating: 4.2,
        calories: 95,
        protein: 7,
        category_name: "Fish",
        customizations: ["Avocado", "Sesame Seeds", "Scallions", "Seaweed Salad"],
      },
      {
        name: "Soy Sauce (Shoyu)",
        description: "Restaurant soy sauce for service and prep",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/030/056/357/large_2x/soy-sauce-bottle-isolated-on-transparent-background-free-png.png",
        price: 19.99,
        rating: 4.6,
        calories: 8,
        protein: 1,
        category_name: "Sauces & Seasonings",
        customizations: ["Extra Wasabi", "Extra Pickled Ginger", "Sesame Seeds", "Scallions"],
      },
      {
        name: "Wasabi Paste",
        description: "Prepared wasabi for nigiri and rolls",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/029/723/835/large_2x/wasabi-paste-isolated-on-transparent-background-free-png.png",
        price: 14.99,
        rating: 4.3,
        calories: 50,
        protein: 2,
        category_name: "Sauces & Seasonings",
        customizations: ["Extra Wasabi", "Extra Pickled Ginger", "Miso Soup"],
      },
      {
        name: "Pickled Ginger (Gari)",
        description: "Ginger slices for palate cleansing",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/028/980/978/large_2x/pickled-ginger-isolated-on-transparent-background-free-png.png",
        price: 16.49,
        rating: 4.2,
        calories: 30,
        protein: 1,
        category_name: "Vegetables & Garnish",
        customizations: ["Extra Pickled Ginger", "Extra Wasabi", "Green Tea"],
      },
      {
        name: "Cucumber",
        description: "Fresh cucumbers for rolls and garnish",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/027/161/587/large_2x/cucumber-isolated-on-transparent-background-free-png.png",
        price: 8.99,
        rating: 4.1,
        calories: 16,
        protein: 1,
        category_name: "Vegetables & Garnish",
        customizations: ["Sesame Seeds", "Scallions", "Avocado", "Seaweed Salad"],
      },
      {
        name: "Avocado (Fresh)",
        description: "Ripe avocados for rolls and bowls",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/027/304/917/large_2x/avocado-isolated-on-transparent-background-free-png.png",
        price: 18.99,
        rating: 4.5,
        calories: 160,
        protein: 2,
        category_name: "Vegetables & Garnish",
        customizations: ["Avocado", "Sesame Seeds", "Scallions", "Seaweed Salad"],
      },
      {
        name: "Asahi Super Dry (Case)",
        description: "Japanese lager (beer) for beverage inventory",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/027/504/719/large_2x/beer-can-isolated-on-transparent-background-free-png.png",
        price: 49.99,
        rating: 4.7,
        calories: 150,
        protein: 2,
        category_name: "Beverages",
        customizations: ["Edamame", "Gyoza", "Seaweed Salad", "Ramune Soda"],
      },
      {
        name: "Sapporo Premium (Case)",
        description: "Japanese beer for service and bar stock",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/027/504/720/large_2x/beer-bottle-isolated-on-transparent-background-free-png.png",
        price: 49.99,
        rating: 4.6,
        calories: 160,
        protein: 2,
        category_name: "Beverages",
        customizations: ["Edamame", "Gyoza", "Seaweed Salad", "Green Tea"],
      },
      {
        name: "Kirin Ichiban (Case)",
        description: "Japanese lager (beer) for beverage inventory",
        image_url:
          "https://static.vecteezy.com/system/resources/previews/027/504/721/large_2x/beer-bottle-isolated-on-transparent-background-free-png.png",
        price: 49.99,
        rating: 4.5,
        calories: 155,
        protein: 2,
        category_name: "Beverages",
        customizations: ["Edamame", "Gyoza", "Miso Soup", "Seaweed Salad"],
      },
    ],
  };
  
  export default dummyData;
  
